// <auto-generated />
namespace WebAPI_DotNetMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class altercolumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(altercolumn));
        
        string IMigrationMetadata.Id
        {
            get { return "202308270350049_alter-column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
